### ISSUE TITLE
[BUG] Incorrect Banner Size on Settings Page

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#728]
## Description
The image size on the settings page has not been updated to match the new dimensions (1500x500) that have been implemented in our codebase. This discrepancy causes the image to strech on the settings page.

## Expected Behavior
The image on the settings page should display at 1500x500 pixels, matching the dimensions specified in our codebase.

## Steps to Reproduce
1. Navigate to `/studio/[organizationSlug]/settings` page
2. Upload a 1500x500 banner
3. Observe as the image gets stretched

## Impact
This issue may cause visual inconsistencies and potentially affect the user experience on the settings page.

**Comment by Mario-SO** [comment]
This requires both front-end and backend changes to ensure that all images (new ones and old ones) are either cropped or resizes to a 1500x500.

The thing is that this will make kinda of a shitty situation:
1. User upload a smaller image
2. User realises that it gets zoomed in
3. User doesn't like the result
4. User uploads a 1500x500 image
5. User happy 😊

This are 2 multimedia writes and reads from the DB for potentially 5MB, same for a bigger image

My proposed solution is **to not let the user upload anything that is not 1500x500** by providing proper feedback, otherwise, as social media like X does, upon uploading  an image, pop a modal where you can adjust the image so we ensure dimensions and also inform the user prior to uploading to DB how the image will look like.

![Image](https://github.com/user-attachments/assets/2d36a2aa-d58b-405f-ad62-55da48ff7bef)
